### ISSUE TITLE
Directory should be removed from Lazy installation code in ReadMe

### ISSUE THREAD

**Issue by bearcatsandor** [ksaito422/remote-line.nvim#11]
If you leave the 'dir =' line in the code it crashes with a runtime error.  See https://www.reddit.com/r/neovim/comments/1fo1bcd/confused_by_lazyvim_syntax_seen_in_some_github/

**Comment by ksaito422** [comment]
@bearcatsandor Apologies, I forgot to remove the development settings. Thank you for reporting this
